# Wrangler configuration for ChittyAuth MCP Agent
# Using Cloudflare's MCP Agent API with stateful capabilities

name = "chittyauth-mcp"
main = "src/mcp-agent.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "web_socket_compression"]
account_id = "bbf9fcd845e78035b7a135c481e88541"

# MCP Agent configuration
[agents]
type = "mcp"

# Routes for MCP WebSocket connections
[[routes]]
pattern = "auth-mcp.chitty.cc/*"
zone_id = "bbf9fcd845e78035b7a135c481e88541"

# KV Namespaces for persistent storage
[[kv_namespaces]]
binding = "AUTH_SESSIONS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "your-auth-tokens-kv-id"
preview_id = "your-preview-auth-tokens-kv-id"

[[kv_namespaces]]
binding = "API_KEYS"
id = "your-api-keys-kv-id"
preview_id = "your-preview-api-keys-kv-id"

# Durable Objects for stateful session management
[[durable_objects.bindings]]
name = "AUTH_STATE"
class_name = "ChittyAuthMCP"
script_name = "chittyauth-mcp"

# SQL database for MCP Agent state persistence
[[d1_databases]]
binding = "AUTH_DB"
database_name = "chittyauth-state"
database_id = "your-d1-database-id"

# Service bindings for ChittyOS integration
[[services]]
binding = "CHITTYID_SERVICE"
service = "chittyid"

[[services]]
binding = "REGISTRY_SERVICE"
service = "chittyregistry"

# Environment variables for development
[env.staging]
name = "chittyauth-mcp-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
CHITTYID_ENDPOINT = "https://id.chitty.cc"
REGISTRY_ENDPOINT = "https://registry.chitty.cc"
CHITTYAUTH_URL = "https://auth.chitty.cc"
CLOUDFLARE_TEAM_DOMAIN = "your-team-domain"
CHITTYOS_DOMAIN = "chitty.cc"
JWT_SECRET = "your-staging-jwt-secret"
SESSION_TIMEOUT = "3600"
MCP_AGENT_VERSION = "1.0.0"

# Environment variables for production
[env.production]
name = "chittyauth-mcp-production"

[env.production.vars]
ENVIRONMENT = "production"
CHITTYID_ENDPOINT = "https://id.chitty.cc"
REGISTRY_ENDPOINT = "https://registry.chitty.cc"
CHITTYAUTH_URL = "https://auth.chitty.cc"
CLOUDFLARE_TEAM_DOMAIN = "your-team-domain"
CHITTYOS_DOMAIN = "chitty.cc"
JWT_SECRET = "your-production-jwt-secret"
SESSION_TIMEOUT = "3600"
MCP_AGENT_VERSION = "1.0.0"

# WebSocket configuration for MCP
[websocket]
max_connections = 1000
idle_timeout = 300

# Analytics and observability
[observability]
enabled = true

[build]
command = "npm run build:mcp"
cwd = "."

# Triggers for cleanup
[triggers]
crons = ["0 */6 * * *"] # Token cleanup every 6 hours