name = "chittyauth-mcp-121"
main = "dist/mcp-agent.js"
compatibility_date = "2024-09-28"
compatibility_flags = ["nodejs_compat"]
account_id = "0bc21e3a5a9de1a4cc843be9c3e98121"

# KV Namespaces for persistent storage
[[kv_namespaces]]
binding = "AUTH_SESSIONS"
id = "dd1dff525a27431aa47844eb364e6606"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "0189885179514d639776ec3bfe8f8274"

[[kv_namespaces]]
binding = "API_KEYS"
id = "41593bb3096745c0b59e0bf6d5cbae20"

# Environment variables for production
[vars]
ENVIRONMENT = "production"
CHITTYID_ENDPOINT = "https://id.chitty.cc"
CHITTYAUTH_URL = "https://auth.chitty.cc"
CHITTYOS_DOMAIN = "chitty.cc"
SESSION_TIMEOUT = "3600"
MCP_AGENT_VERSION = "1.0.0"

[build]
command = "npm run build:mcp"