# Simple Wrangler configuration for ChittyAuth OAuth integration
name = "chittyauth"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "0bc21e3a5a9de1a4cc843be9c3e98121"

# Production routes
routes = [
  { pattern = "auth.chitty.cc/*", zone_name = "chitty.cc" },
  { pattern = "id.chitty.cc/*", zone_name = "chitty.cc" }
]

# Environment variables for OAuth integration
[vars]
ENVIRONMENT = "production"
CHITTYID_SERVICE_URL = "https://id.chitty.cc"
CHITTYOS_DOMAIN = "chitty.cc"
PORTAL_DOMAIN = "portal.chitty.cc"
MCP_PORTAL_ENABLED = "true"
CROSS_SYNC_ENABLED = "true"
SESSION_TIMEOUT = "3600"
JWT_SECRET = "production-jwt-secret-key"
AUTH_SALT = "production-auth-salt-key"

# Build configuration
[build]
command = "npm run build"
cwd = "."