# Wrangler configuration for ChittyAuth Service

name = "chittyauth"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "0bc21e3a5a9de1a4cc843be9c3e98121"

# KV Namespaces for session and token storage
[[kv_namespaces]]
binding = "AUTH_SESSIONS"
id = "dd1dff525a27431aa47844eb364e6606"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "0189885179514d639776ec3bfe8f8274"

[[kv_namespaces]]
binding = "API_KEYS"
id = "41593bb3096745c0b59e0bf6d5cbae20"

# Durable Objects for session management (removed for now)

# Environment variables for development
[env.staging]
name = "chittyauth-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
CHITTYID_SERVICE_URL = "https://id.chitty.cc"
REGISTRY_SERVICE_URL = "https://registry.chitty.cc"
CHITTYOS_ACCOUNT_ID = "0bc21e3a5a9de1a4cc843be9c3e98121"
CLOUDFLARE_TEAM_DOMAIN = "chittycorp"
CHITTYOS_DOMAIN = "chitty.cc"
SESSION_TIMEOUT = "3600"

# Environment variables for production
[env.production]
name = "chittyauth-production"

[[env.production.routes]]
pattern = "auth.chitty.cc/*"
zone_name = "chitty.cc"

[env.production.vars]
ENVIRONMENT = "production"
CHITTYID_SERVICE_URL = "https://id.chitty.cc"
REGISTRY_SERVICE_URL = "https://registry.chitty.cc"
CHITTYOS_ACCOUNT_ID = "0bc21e3a5a9de1a4cc843be9c3e98121"
CLOUDFLARE_TEAM_DOMAIN = "chittycorp"
CHITTYOS_DOMAIN = "chitty.cc"
SESSION_TIMEOUT = "3600"

# Service bindings for ChittyOS integration
[[services]]
binding = "CHITTYID_SERVICE"
service = "chittyid"

[[services]]
binding = "REGISTRY_SERVICE"
service = "chittyregistry"

# Analytics and logging
[observability]
enabled = true

[build]
command = "npm run build"
cwd = "."

# Deployment configuration (cron removed for now)