/**
 * ChittyID Foundation Service Client
 * Per Charter: All ChittyIDs must be generated by Foundation service
 * NO LOCAL GENERATION ALLOWED
 */
export type ChittyNamespace =
  | "PEO" // People
  | "PET" // Pets
  | "PROP" // Property
  | "PLACE" // Places
  | "AI" // AI Instances
  | "EVID" // Evidence
  | "FACT" // Facts
  | "CASE" // Cases
  | "USER"; // System Users

// Map namespaces to Foundation entity types
const NAMESPACE_TO_ENTITY_MAP: Record<ChittyNamespace, string> = {
  PEO: "PERSON",
  PET: "THING",
  PROP: "THING",
  PLACE: "LOCATION",
  AI: "THING",
  EVID: "THING",
  FACT: "THING",
  CASE: "EVENT",
  USER: "PERSON",
};

/**
 * Request ChittyID from Foundation service (Foundation generates it)
 * @param namespace - The entity namespace
 * @param input - Unique identifier for the entity
 * @returns Promise<string> - ChittyID from Foundation service
 */
export async function chittyId(
  namespace: ChittyNamespace,
  input: string,
): Promise<string> {
  const foundationUrl =
    process.env.CHITTYID_FOUNDATION_URL ||
    "https://chittyid-foundation.workers.dev";
  const apiKey = process.env.CHITTY_ID_TOKEN || process.env.CHITTYID_API_KEY;

  if (!apiKey) {
    throw new Error("CHITTY_ID_TOKEN required for Foundation ChittyID service");
  }

  try {
    const response = await fetch(`${foundationUrl}/api/v2/chittyid/mint`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        entity: NAMESPACE_TO_ENTITY_MAP[namespace],
        name: input,
        format: "simple", // Use simple format for compatibility
        metadata: {
          namespace,
          source: "chittyschema",
          originalInput: input,
        },
      }),
    });

    if (!response.ok) {
      throw new Error(`Foundation ChittyID service error: ${response.status}`);
    }

    const result = await response.json();
    return result.chitty_id; // v2 API uses chitty_id field
  } catch (error) {
    console.error("Error calling Foundation ChittyID service:", error);
    throw new Error(
      "ChittyID generation requires Foundation service. Local generation is prohibited.",
    );
  }
}

/**
 * Validate ChittyID format (supports both Foundation formats)
 * @param id - The ChittyID to validate
 * @returns Promise<boolean> - Validation result from Foundation service
 */
export async function isValidChittyId(id: string): Promise<boolean> {
  const foundationUrl =
    process.env.CHITTYID_FOUNDATION_URL ||
    "https://chittyid-foundation.workers.dev";
  const apiKey = process.env.CHITTY_ID_TOKEN || process.env.CHITTYID_API_KEY;

  // Basic format check first
  const simplePattern = /^CHITTY-[A-Z]+-[0-9]{6}-[A-F0-9]{8}$/;
  const officialPattern =
    /^(CP|CL|CT|CE)-[A-Z0-9]-[A-Z0-9]{3}-[0-9]{4}-[PLTE]-[0-9]{4}-[A-Z]-[0-9]{2}$/;

  if (!simplePattern.test(id) && !officialPattern.test(id)) {
    return false;
  }

  // Use Foundation service for full validation if available
  if (apiKey) {
    try {
      const response = await fetch(`${foundationUrl}/api/v2/chittyid/verify`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`,
        },
        body: JSON.stringify({ chittyId: id }),
      });

      if (response.ok) {
        const result = await response.json();
        return result.valid;
      }
    } catch (error) {
      console.warn(
        "Foundation validation unavailable, using format check:",
        error,
      );
    }
  }

  // Fallback to format validation
  return simplePattern.test(id) || officialPattern.test(id);
}

/**
 * Legacy sync function for backward compatibility
 * @deprecated Use async chittyId() instead
 */
export function chittyIdSync(
  _namespace: ChittyNamespace,
  _input: string,
): string {
  throw new Error(
    "Synchronous ChittyID generation is prohibited. Use async chittyId() with Foundation service.",
  );
}

/**
 * Extract namespace from a ChittyID
 * @param id - The ChittyID
 * @returns The namespace or null if invalid
 */
export function extractNamespace(id: string): ChittyNamespace | null {
  const match = id.match(
    /^CHITTY-(PEO|PET|PROP|PLACE|AI|EVID|FACT|CASE|USER)-/,
  );
  return match ? (match[1] as ChittyNamespace) : null;
}

// Example usage:
// chittyId('PROP', 'PIN:14-21-111-008-1006') -> 'CHITTY-PROP-1A2B3C4D5E6F7890'
// chittyId('PEO', 'john.doe@example.com') -> 'CHITTY-PEO-9F8E7D6C5B4A3210'
// chittyId('AI', 'claude-opus-4.1:instance:12345') -> 'CHITTY-AI-FEDCBA9876543210'
